services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "//localhost:3000/api/afisha"
        VITE_CDN_URL: "//localhost:3000/content/afisha"
    container_name: "frontend"
    image: ghcr.io/olgakladova/film-react-nest/frontend:latest
    networks:
      - front
    volumes:
      - frontend_dist:/usr/www/frontend/dist
    
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    image: ghcr.io/olgakladova/film-react-nest/backend:latest
    networks:
      - webnet
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: postgres
      DATABASE_NAME: prac
      DATABASE_PORT: 5432
      DATABASE_USERNAME: prac
      DATABASE_PASSWORD: prac
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    image: "postgres:latest"
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - webnet
      - postgres

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ZelyonayaLuna@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: prac
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/usr/app:ro
    depends_on:
      - backend
    networks:
      - webnet
      - front

volumes:
  frontend_dist:
  pg_data:
  pgadmin:

networks:
  webnet:
  postgres:
  front:
 
